CREATE TABLE `rally_tournament` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `biz_id` VARCHAR(32) NOT NULL COMMENT '雪花ID',
    `tournament_name` VARCHAR(128) NOT NULL COMMENT '赛事名称',
    `poster_key` VARCHAR(256) DEFAULT NULL COMMENT '活动海报图片key（对象存储）',
    `rule_poster_key` VARCHAR(256) DEFAULT NULL COMMENT '规则海报图片key（对象存储）',
    `wechat_group_qr_code_key` VARCHAR(256) DEFAULT NULL COMMENT '微信群拉群二维码图片key（对象存储）',
    `match_type` VARCHAR(16) NOT NULL COMMENT '比赛类型：SINGLE/DOUBLE',
    `city_code` VARCHAR(16) NOT NULL COMMENT '城市编码',
    `city_name` VARCHAR(32) NOT NULL COMMENT '城市名称',
    `ntrp_level` VARCHAR(16) NOT NULL COMMENT 'NTRP等级：3.0/3.5/4.0...',
    `gender_limit` VARCHAR(16) NOT NULL COMMENT '性别限制：ALL/MALE/FEMALE',
    `total_slots` INT NOT NULL COMMENT '正赛签位：16/32/64',
    `offline_from_round` VARCHAR(16) NOT NULL COMMENT '几强后转线下：ROUND_4/ROUND_8/ROUND_16',
    `offline_meetup_id` VARCHAR(32) DEFAULT NULL COMMENT '线下赛活动的约球bizId',
    `qualifier_group_size` INT NOT NULL DEFAULT 2 COMMENT '资格赛每组人数，默认2，可设3',
    `entry_fee` BIGINT NOT NULL COMMENT '报名费，单位：分',
    `prize_money` VARCHAR(256) DEFAULT NULL COMMENT '奖金配置，逗号分隔，第1个为第一名奖金，第2个为第二名奖金，依此类推，单位：分',
    `registration_start_time` DATETIME NOT NULL COMMENT '报名开始时间',
    `registration_end_time` DATETIME DEFAULT NULL COMMENT '报名截止时间，可空',
    `qualifier_start_time` DATETIME NOT NULL COMMENT '资格赛开始时间',
    `qualifier_end_time` DATETIME DEFAULT NULL COMMENT '资格赛截止时间，可空表示永久有效',
    `end_time` DATETIME DEFAULT NULL COMMENT '赛事结束时间，赛事结束后写入',
    `qualifier_reject_limit` INT NOT NULL DEFAULT 1 COMMENT '资格赛阶段拒绝次数上限',
    `main_draw_reject_limit` INT NOT NULL DEFAULT 1 COMMENT '正赛阶段拒绝次数上限',
    `match_rule_description` TEXT DEFAULT NULL COMMENT '比赛规则描述，纯文本，支持\n换行',
    `ext_data` JSON DEFAULT NULL COMMENT '赛事扩展数据，当前存储主题颜色：buttonColor、backgroundColor',
    `status` VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT/ACTIVE/ABANDONED',
    `current_filled_slots` INT NOT NULL DEFAULT 0 COMMENT '当前已支付锁定的正赛席位数',
    `current_round` VARCHAR(16) DEFAULT NULL COMMENT '当前进行中轮次：QUALIFIER/ROUND_64/ROUND_32/ROUND_16/ROUND_8/ROUND_4/FINAL，由结果确认推进',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_id` (`biz_id`),
    KEY `idx_city_status` (`city_code`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='赛事表';
