CREATE TABLE `rally_tournament_match` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `biz_id` VARCHAR(32) NOT NULL COMMENT '雪花ID',
    `tournament_id` VARCHAR(32) NOT NULL COMMENT '赛事bizId',
    `match_no` INT NOT NULL COMMENT '赛事内展示编号，同一赛事内从1开始递增，前端展示补零为3位（如001/002），不跨赛事全局唯一',
    `round` VARCHAR(16) NOT NULL COMMENT '轮次：QUALIFIER/ROUND_32/...',
    `group_size` INT NOT NULL DEFAULT 2 COMMENT '本场人数（2或3）',
    `court_booker_id` VARCHAR(32) DEFAULT NULL COMMENT '订场人用户ID',
    `court_booker_selected_time` DATETIME DEFAULT NULL COMMENT '订场人确定时间',
    `schedule_submitted_time` DATETIME DEFAULT NULL COMMENT '订场人提交赛约、进入SCHEDULED状态的时间，用于超时判定，每次退回BOOKING重新提交会更新',
    `meetup_id` VARCHAR(32) DEFAULT NULL COMMENT '关联约球活动bizId，订场时创建草稿约球，场地/时间/费用等均以约球为准',
    `winner_entry_no` INT DEFAULT NULL COMMENT '结果提交时选定的获胜方报名编号',
    `submitted_by` VARCHAR(32) DEFAULT NULL COMMENT '结果提交人用户ID',
    `submitted_time` DATETIME DEFAULT NULL COMMENT '结果提交时间',
    `reject_phase` VARCHAR(16) DEFAULT NULL COMMENT '终止比赛的拒绝发生阶段：SCHEDULE_REJECT(拒绝比赛)/RESULT_REJECT(拒绝结果)，仅终止比赛时写入',
    `reject_reason_code` VARCHAR(32) DEFAULT NULL COMMENT '拒绝理由编码，见理由预设表',
    `rejected_by` VARCHAR(32) DEFAULT NULL COMMENT '拒绝人用户ID',
    `rejected_time` DATETIME DEFAULT NULL COMMENT '拒绝时间',
    `last_rebook_by` VARCHAR(32) DEFAULT NULL COMMENT '最近一次打回重订的用户ID，打回不终止比赛，不留历史只记最近一次',
    `last_rebook_reason_code` VARCHAR(32) DEFAULT NULL COMMENT '打回理由编码',
    `last_rebook_time` DATETIME DEFAULT NULL COMMENT '打回时间',
    `status` VARCHAR(16) NOT NULL DEFAULT 'MATCHED' COMMENT '状态：MATCHED/BOOKING/SCHEDULED/PENDING_CONFIRM/COMPLETED/REJECTED',
    `matched_time` DATETIME NOT NULL COMMENT '匹配时间',
    `completed_time` DATETIME DEFAULT NULL COMMENT '完成时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号，防止订场人身份并发抢占等重复操作',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_id` (`biz_id`),
    UNIQUE KEY `uk_tournament_match_no` (`tournament_id`, `match_no`),
    KEY `idx_tournament_round` (`tournament_id`, `round`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='赛事比赛表';
