CREATE TABLE `rally_court` (
  `id`             BIGINT       NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `biz_id`         VARCHAR(32)  NOT NULL COMMENT '业务主键（雪花算法字符串）',
  `name`           VARCHAR(128) NOT NULL COMMENT '球场名称',
  `alias`          VARCHAR(128) DEFAULT NULL COMMENT '球场别名',
  `address`        VARCHAR(256) DEFAULT NULL COMMENT '球场详细地址',
  `lng`            DOUBLE       DEFAULT NULL COMMENT '球场经度',
  `lat`            DOUBLE       DEFAULT NULL COMMENT '球场纬度',
  `city_code`      VARCHAR(32)  NOT NULL COMMENT '城市编码',
  `district_code`  VARCHAR(32)  DEFAULT NULL COMMENT '区域编码，选填',
  `remark`         VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `type`           VARCHAR(32)  DEFAULT NULL COMMENT '球场环境：INDOOR 室内 / OUTDOOR 室外',
  `surface`        VARCHAR(32)  DEFAULT NULL COMMENT '场地材质：HARD 硬地 / CLAY 红土 / GRASS 草地',
  `tags`           VARCHAR(512) DEFAULT NULL COMMENT '标签，逗号分隔，如：硬地,有遮蔽',
  `city_name`      VARCHAR(64)  DEFAULT NULL COMMENT '城市名称',
  `district_name`  VARCHAR(64)  DEFAULT NULL COMMENT '区域名称',
  `ext_data`       TEXT         DEFAULT NULL COMMENT '扩展数据，JSON格式，存储拼音等信息',
  `source`         VARCHAR(32)  NOT NULL DEFAULT 'SYSTEM' COMMENT '来源：USER_PUBLISH 用户发布 / SYSTEM 系统录入',
  `source_id`      VARCHAR(128) DEFAULT NULL COMMENT '三方来源ID，用于标识球场在第三方系统中的唯一ID',
  `status`         VARCHAR(32)  NOT NULL DEFAULT 'COLLECTED' COMMENT '状态：COLLECTED 已收录待审核 / ACTIVE 可用 / DISABLED 已停用',
  `meetup_count`   INT          DEFAULT 0 COMMENT '约球次数统计',
  `create_time`    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time`    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_id` (`biz_id`),
  UNIQUE KEY `uk_source_id` (`source_id`),
  KEY `idx_city_district` (`city_code`, `district_code`) COMMENT '按城市/区域查询球场'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='球场信息表';
