CREATE TABLE `rally_meetup` (
  `id`              BIGINT       NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `biz_id`          VARCHAR(32)  NOT NULL COMMENT '业务主键（雪花算法字符串）',
  `meetup_type`     VARCHAR(16)  NOT NULL DEFAULT 'NORMAL' COMMENT '约球类型：NORMAL/TOURNAMENT',
  `creator_id`      VARCHAR(32)  NOT NULL COMMENT '发布者，关联 users.user_id',
  `title`           VARCHAR(128) DEFAULT NULL COMMENT '标题，选填；不填后端按模板生成',
  `match_type`      varchar(8) NOT NULL DEFAULT 'single' COMMENT '类型：单打/双打/拉球',
  `max_players`     INT          NOT NULL COMMENT '人数上限',
  `current_players` INT          NOT NULL DEFAULT 1 COMMENT '已加入人数（含发布者，发布即 1）',
  `city_code`       VARCHAR(32)  NOT NULL COMMENT '城市编码，由 court_location 反查后端写入',
  `city_name`       VARCHAR(64)  NOT NULL COMMENT '城市名称',
  `district_name`   VARCHAR(64)  DEFAULT NULL COMMENT '区域名称，选填',
  `start_time`      DATETIME     NOT NULL COMMENT '活动开始时间（含日期，+08:00）',
  `end_time`        DATETIME     NOT NULL COMMENT '结束时间 = start_time + duration 小时，懒判定/兜底查询用（裁定 D3/D4）',
  `duration`        DECIMAL(3,1) NOT NULL COMMENT '持续小时：0.5/1.0/1.5/2.0/2.5/3.0',
  `court_name`      VARCHAR(128) DEFAULT NULL COMMENT '场地名称，手填',
  `court_address`   VARCHAR(256) NOT NULL COMMENT '场地详细地址，手填或地图点选',
  `court_lng`       DOUBLE       NOT NULL COMMENT '场地经度',
  `court_lat`       DOUBLE       NOT NULL COMMENT '场地纬度',
  `court_select_mode` VARCHAR(8) DEFAULT NULL COMMENT '球场选择模式：TEXT/MAP/FREE',
  `court_id`        VARCHAR(32)  DEFAULT NULL COMMENT '球场库ID，TEXT/MAP模式下从球场库选中时传入',
  `level_mode`      varchar(8) DEFAULT 'exact' COMMENT '水平要求模式',
  `level_min`       DECIMAL(3,1) DEFAULT NULL COMMENT '水平最小值，RANGE/EXACT/ABOVE 必填',
  `level_max`       DECIMAL(3,1) DEFAULT NULL COMMENT '水平最大值，RANGE/EXACT/BELOW 必填',
  `gender_limit`    varchar(8) NOT NULL DEFAULT 'any' COMMENT '性别限制',
  `join_mode`       varchar(8) NOT NULL DEFAULT 'direct' COMMENT '加入模式：直接/审批',
  `cost_data`       JSON         DEFAULT NULL COMMENT '费用数据 {costItems:[{name,totalAmount(分)}], hourlyAllocations:[{duration,userIds}]}',
  `status`          varchar(16) NOT NULL DEFAULT 'open' COMMENT '状态机',
  `court_index`     VARCHAR(64)  DEFAULT NULL COMMENT '场地索引，前端透传存储',
  `create_time`     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time`     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_id` (`biz_id`),
  KEY `idx_creator` (`creator_id`),
  KEY `idx_city_status_end` (`city_code`, `status`, `end_time`) COMMENT '列表懒判定过滤主索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='约球主表';
