CREATE TABLE `rally_tournament_entry` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `biz_id` VARCHAR(32) NOT NULL COMMENT '雪花ID',
    `tournament_id` VARCHAR(32) NOT NULL COMMENT '赛事bizId',
    `user_id` VARCHAR(32) NOT NULL COMMENT '用户ID',
    `partner_id` VARCHAR(32) DEFAULT NULL COMMENT '双打搭档用户ID',
    `entry_no` INT NOT NULL COMMENT '报名编号，赛事内从1递增，双打搭档共享同一编号，前端展示补零3位（如001），超999不限制继续递增',
    `preferred_districts` VARCHAR(512) DEFAULT NULL COMMENT '活动区域，JSON数组',
    `court_ability` VARCHAR(16) NOT NULL COMMENT '场地能力：CAN_BOOK/CANNOT_BOOK',
    `available_times` VARCHAR(512) DEFAULT NULL COMMENT '可比赛时间，JSON数组',
    `stage` VARCHAR(8) NOT NULL DEFAULT 'QUALIFY' COMMENT '阶段：QUALIFY(资格赛)/MAIN(正赛)',
    `status` VARCHAR(16) NOT NULL DEFAULT 'WAITING' COMMENT '状态：WAITING(排队匹配)/FROZEN(冻结)/IN_MATCH(比赛中)/PAYING(待支付，仅QUALIFY阶段)/CHAMPION(冠军)/ELIMINATED(淘汰)/WITHDRAWN(主动退出)',
    `current_round` VARCHAR(16) NOT NULL DEFAULT 'QUALIFIER' COMMENT '当前轮次：QUALIFIER/ROUND_32/ROUND_16/ROUND_8/ROUND_4/FINAL',
    `qualifier_reject_count` INT NOT NULL DEFAULT 0 COMMENT '资格赛阶段已拒绝次数',
    `main_draw_reject_count` INT NOT NULL DEFAULT 0 COMMENT '正赛阶段已拒绝次数',
    `qualified_time` DATETIME DEFAULT NULL COMMENT '获得正赛资格时间',
    `paid_time` DATETIME DEFAULT NULL COMMENT '支付时间（正赛席位锁定时间）',
    `last_visit_time` DATETIME DEFAULT NULL COMMENT '用户最近一次打开本赛事详情的时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_id` (`biz_id`),
    UNIQUE KEY `uk_tournament_user` (`tournament_id`, `user_id`),
    KEY `idx_tournament_entry_no` (`tournament_id`, `entry_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='赛事报名表';
