CREATE TABLE `rally_meetup_score` (
  `id`              BIGINT      NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `biz_id`          VARCHAR(32) NOT NULL COMMENT '业务唯一 ID（雪花算法字符串）',
  `rally_meetup_id` VARCHAR(32) NOT NULL COMMENT '关联 rally_meetup.biz_id',
  `set_number`      INT         NOT NULL COMMENT '第几盘，从 1 开始',
  `set_format`      VARCHAR(16) NOT NULL COMMENT '赛制：GAME / TIEBREAK',
  `match_type`      VARCHAR(16) NOT NULL DEFAULT '' COMMENT '比赛类型：SINGLE / DOUBLE / RALLY',
  `meetup_date`     DATETIME    DEFAULT NULL COMMENT '比赛日期（冗余自 rally_meetup.start_time）',
  `side_a_player1`  VARCHAR(32) NOT NULL COMMENT 'A 侧选手1 user_id（裁定 D13，单个）',
  `side_a_player1_nickname` VARCHAR(128) DEFAULT '' COMMENT 'A 侧选手1昵称（冗余存储）',
  `side_a_player1_avatar` VARCHAR(512) DEFAULT '' COMMENT 'A 侧选手1头像URL（冗余存储）',
  `side_a_player1_gender` VARCHAR(16)  DEFAULT NULL COMMENT 'A 侧选手1性别（冗余存储）',
  `side_a_player2`  VARCHAR(32) DEFAULT NULL COMMENT 'A 侧选手2 user_id，单打为 NULL',
  `side_a_player2_nickname` VARCHAR(128) DEFAULT '' COMMENT 'A 侧选手2昵称（冗余存储）',
  `side_a_player2_avatar` VARCHAR(512) DEFAULT '' COMMENT 'A 侧选手2头像URL（冗余存储）',
  `side_a_player2_gender` VARCHAR(16)  DEFAULT NULL COMMENT 'A 侧选手2性别（冗余存储）',
  `side_b_player1`  VARCHAR(32) NOT NULL COMMENT 'B 侧选手1 user_id',
  `side_b_player1_nickname` VARCHAR(128) DEFAULT '' COMMENT 'B 侧选手1昵称（冗余存储）',
  `side_b_player1_avatar` VARCHAR(512) DEFAULT '' COMMENT 'B 侧选手1头像URL（冗余存储）',
  `side_b_player1_gender` VARCHAR(16)  DEFAULT NULL COMMENT 'B 侧选手1性别（冗余存储）',
  `side_b_player2`  VARCHAR(32) DEFAULT NULL COMMENT 'B 侧选手2 user_id，单打为 NULL',
  `side_b_player2_nickname` VARCHAR(128) DEFAULT '' COMMENT 'B 侧选手2昵称（冗余存储）',
  `side_b_player2_avatar` VARCHAR(512) DEFAULT '' COMMENT 'B 侧选手2头像URL（冗余存储）',
  `side_b_player2_gender` VARCHAR(16)  DEFAULT NULL COMMENT 'B 侧选手2性别（冗余存储）',
  `side_a_score`    INT         NOT NULL COMMENT 'A 侧本盘比分（局数/抢七分）',
  `side_b_score`    INT         NOT NULL COMMENT 'B 侧本盘比分',
  `side_a_tiebreak_score` INT   DEFAULT NULL COMMENT 'A 侧抢七比分（本盘 6:6 时记录）',
  `side_b_tiebreak_score` INT   DEFAULT NULL COMMENT 'B 侧抢七比分（本盘 6:6 时记录）',
  `win_side`        VARCHAR(4)  NOT NULL DEFAULT '' COMMENT '获胜边: A / B',
  `recorded_by`     VARCHAR(32) NOT NULL COMMENT '记录人 user_id（任意参与者可代记）',
  `version`         INT         NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  `create_time`     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time`     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_id` (`biz_id`),
  UNIQUE KEY `uk_meetup_set` (`rally_meetup_id`,`set_number`) COMMENT '同场同盘唯一',
  KEY `idx_meetup` (`rally_meetup_id`) COMMENT '按场查全部盘'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='比分记录表（按盘，双侧选手，乐观锁）';
