CREATE TABLE tour_tournament (
    id           BIGINT        NOT NULL AUTO_INCREMENT,
    tournament_id VARCHAR(50)  COMMENT '外部API返回的赛事ID，如 1536',
    year         INT           NOT NULL DEFAULT 2026 COMMENT '赛事年份',
    name         VARCHAR(100)  NOT NULL COMMENT '赛事名称，如 Wimbledon',
    tour VARCHAR(10) NOT NULL  DEFAULT 'ATP' COMMENT 'ATP / WTA / ITF/ Grand',
    category     VARCHAR(20)   DEFAULT ''  NOT NULL COMMENT '',
    surface      VARCHAR(10)   NOT NULL COMMENT '',
    city         VARCHAR(50)   NOT NULL,
    country      VARCHAR(32)   COMMENT '',
    prize_money  INT           COMMENT '总奖金（USD）',
    prize_money_text  VARCHAR(50)    COMMENT '总奖金文本',
    status       VARCHAR(20)   NOT NULL DEFAULT 'active' COMMENT 'active / completed',
    start_date   DATE          NOT NULL,
    end_date     DATE          NOT NULL,
    image_path      VARCHAR(255)   NOT NULL DEFAULT '' COMMENT '主图',
    background_path      VARCHAR(255)   NOT NULL DEFAULT '' COMMENT '背景图',
    create_time   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tour_tournament_tournament_year (tournament_id, year),
    INDEX idx_tour_tournament_date     (start_date, end_date),
    INDEX idx_tour_tournament_status   (status),
    INDEX idx_tour_tournament_category (category),
    INDEX idx_tour_tournament_year     (year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='赛事主信息';
