CREATE TABLE tour_match (
    id               BIGINT      NOT NULL AUTO_INCREMENT,
    match_id         VARCHAR(50) NOT NULL COMMENT '外部API返回的比赛ID，如 MS008',
    match_index      INT         COMMENT '比赛序号，从 match_id 中提取的数字部分，如 MS008 → 8',
    draw_id          BIGINT      NOT NULL COMMENT '签表ID',
    tournament_id    VARCHAR(50) NOT NULL COMMENT '外部赛事ID，便于按赛事查询',
    year             INT         NOT NULL COMMENT '赛事年份',
    round_number     TINYINT     COMMENT '轮次序号：1=首轮，7=决赛（128签）',
    round_name       VARCHAR(32) COMMENT 'R128 / R64 / R32 / R16 / QF / SF / F',
    player1_id       VARCHAR(50) COMMENT '外部球员ID，未确定对阵时允许为 NULL',
    player2_id       VARCHAR(50) COMMENT '外部球员ID，同上',
    winner_id        VARCHAR(50) COMMENT '外部球员ID，比赛结束前为 NULL',
    scheduled_at     DATETIME    COMMENT '计划开赛时间',
    scheduled_at_text VARCHAR(50) COMMENT 'NotBefore文本，如 Starts At',
    started_at       DATETIME    COMMENT '实际开始时间',
    ended_at         DATETIME    COMMENT '实际结束时间',
    court            VARCHAR(50) COMMENT '场地名称，如 Centre Court',
    court_seq        TINYINT     COMMENT '该球场第几场比赛',
    status           VARCHAR(20) NOT NULL DEFAULT '' COMMENT '',
    duration_minutes SMALLINT    COMMENT '比赛时长（分钟）',
    description TEXT COMMENT '比赛描述',
    match_date DATE COMMENT '比赛日期，从MatchDate中提取',
    sets_json JSON COMMENT '比赛各盘比分完整快照（player1/player2 方向）',
    create_time       DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time       DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tour_match_match_id (match_id, draw_id),
    INDEX idx_tour_match_draw        (draw_id, round_number),
    INDEX idx_tour_match_tournament  (tournament_id),
    INDEX idx_tour_match_tournament_year (tournament_id, year),
    INDEX idx_tour_match_player1     (player1_id),
    INDEX idx_tour_match_player2     (player2_id),
    INDEX idx_tour_match_status_time (status, scheduled_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='具体比赛场次';
